### ISSUE TITLE
It takes a long time from submitting make_trade to approve

### ISSUE THREAD

**Issue by snailAlice** [uniswap-python/uniswap-python#167]
When I execute a new transaction, it took more than 1 minute from the initiation of the transaction to the approve. How can I shorten the approve phase of a contract address that has never been traded?

**Comment by snailAlice** [comment]
It took 16s on pancakeswap,but it took more than 1 minute on uinswap-v2 from the initiation of the transaction to the approve.

**Comment by liquid-8** [comment]
Set up local node, for example.

**Comment by liquid-8** [comment]
https://geth.ethereum.org/docs/install-and-build/installing-geth
Light sync mode is more than OK for development in the most cases.

Also please that your problem might be caused by your gas price strategy. I.E. if you set price that is close to mid-priority then it takes 1 minute+ to get TX mined. Also average time to mine 1 block at ether mainnet is about 14 seconds VS ~6 seconds at BSC (i don't remember exact numbers for BSC but it is smth like that). Nevertheless, having local node is quite desirable.
