### ISSUE TITLE
Web3.py only accepts checksum addresses.

### ISSUE THREAD

**Issue by TangMonk** [uniswap-python/uniswap-python#262]
If I get price with dai, it works
```
eth = "0x0000000000000000000000000000000000000000"
dai = "0x6B175474E89094C44Da98b954EedeAC495271d0F"

print(uniswap.get_price_output(dai, eth, 1 * 10**18))
```

But If I get price with usdc, with error:
```
eth = "0x0000000000000000000000000000000000000000"
usdc = "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"

print(uniswap.get_price_output(dai, eth, 1 * 10**18))

->>
web3.exceptions.InvalidAddress: ('Web3.py only accepts checksum addresses. The software that gave you this non-checksum address should be considered unsafe, please file it as a bug on their platform. Try using an ENS name instead. Or, if you must accept lower safety, use Web3.toChecksumAddress(lower_case_address).'
```

**Comment by ErikBjare** [comment]
This is not a bug. The error message tells you what to do.

**Comment by ErikBjare** [comment]
Because one is a checksum address, and one is not.

Checksum addressed use capitalization to store a checksum of the addresses, so if an address is all-lowercase or all-uppercase, it is not a checksum address.

The function transforms a non-checksummed address into a checksummed one. You can verify this easily by printing the result, and use that instead of the original address.

**Comment by TangMonk** [comment]
Ok, thanks for you patient explain
